/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include "stdafx.h"
#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus


#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_accept[267] =
    {   0,
        0,    0,   75,   75,    0,    0,   90,   89,    2,   76,
       89,   73,   66,   67,   58,   56,   70,   57,   71,   60,
       86,   72,   63,   55,   62,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   59,   61,   85,   68,   69,    1,   75,   74,   77,
       78,   81,   77,    0,    0,   86,   65,   64,   85,    5,
       85,   85,   85,   85,   85,   85,   33,   85,   85,   85,
       85,   85,   85,    8,   45,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   43,   85,   85,   85,   85,
       85,    1,   75,   77,   79,   77,   87,   88,   85,   85,

       85,   85,   85,   85,    3,   85,   85,   85,   85,   85,
       42,   85,   85,   85,   47,   25,   85,   85,   85,   85,
       85,   85,   85,   17,   85,   85,   85,   85,   19,   85,
       85,   85,   85,   85,   85,   85,   26,   85,   27,   85,
       11,    0,   34,   85,   85,    0,   85,   85,   39,   85,
       44,   85,   51,   85,   85,   40,   85,    0,   85,    9,
       85,    6,   85,   85,   85,   85,   85,   85,   14,   20,
       85,   28,   85,    0,    0,    0,    0,    0,    0,    0,
       85,    7,    0,   85,   85,   85,   85,   85,   85,   85,
       85,    0,   85,   22,   31,   30,   49,   85,   83,   85,

       85,   10,    0,    0,   12,    0,    0,    0,    0,    0,
       85,    0,   85,   85,   32,   85,   85,   15,   29,   46,
        0,   53,   85,   82,   23,   48,    0,    0,    0,    0,
       18,   21,    0,   85,    0,   85,   24,   85,   85,    0,
       85,   35,    0,    0,    0,    0,   85,   41,   13,   84,
       52,    0,   85,    0,    0,    0,   38,   54,    4,   50,
        0,   36,   37,    0,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   16,   16,   17,    1,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   27,   27,   30,   31,   32,   33,   27,
       27,   34,   35,   36,   37,   38,   39,   27,   27,   27,
        1,   40,    1,   41,   27,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   27,   27,   51,   52,   53,
       54,   55,   27,   56,   57,   58,   59,   60,   61,   62,
       63,   27,   64,    1,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1
    } ;

static yyconst short int yy_base[272] =
    {   0,
        0,    0,  319,  318,   64,   66,  320,  323,  323,  323,
       43,  323,  323,  323,  323,  323,  323,  323,  323,  323,
       57,  323,  300,  323,  299,  260,   20,   33,   27,   27,
       37,    0,   37,  262,  261,   39,  268,   42,   43,  260,
       37,  323,  323,  269,  323,  323,  245,    0,  323,    0,
      323,  306,  243,   87,  293,   79,  323,  323,    0,    0,
      253,  268,   49,  263,  251,  251,    0,  245,   59,  257,
      249,  243,  245,    0,  239,  242,  250,   53,  243,   75,
      242,   70,  249,  234,   73,    0,   61,  232,  239,  238,
       98,  221,    0,    0,  323,  220,  120,  270,  233,  241,

      236,  237,  224,  222,    0,  232,  120,  225,  230,  218,
      125,  230,  227,  217,  212,    0,  212,  218,  223,  208,
      220,  210,  214,  135,  205,  209,  207,  214,    0,  209,
      207,  199,  200,  213,  208,  202,    0,  203,    0,   93,
      222,  123,    0,  195,  203,  223,  189,  198,    0,  194,
        0,  221,  213,  186,  197,    0,  187,  208,  192,    0,
      176,    0,  185,  189,  188,  203,  189,  189,    0,    0,
      179,    0,  182,  175,  168,  179,  171,   94,  168,  174,
      164,    0,  179,  170,  173,  172,  168,  166,  162,  156,
      165,  170,  159,    0,    0,    0,  180,  162,    0,  155,

      161,    0,  147,  152,  323,  159,  152,  159,  138,  150,
      149,  154,  143,  140,    0,  153,  141,    0,    0,    0,
      143,    0,  142,    0,    0,    0,  139,  146,  130,  142,
      323,  323,  136,  132,  136,  131,    0,  127,  136,  128,
      127,  323,  121,  126,  132,  126,  108,  323,    0,    0,
        0,  157,  111,  106,  109,   92,  323,    0,  323,    0,
       85,  323,  323,   78,  323,  323,  162,  166,  121,  170,
      174
    } ;

static yyconst short int yy_def[272] =
    {   0,
      266,    1,  267,  267,  268,  268,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  266,  266,  269,  266,  266,  266,  270,  266,  271,
      266,  266,  271,  266,  266,  266,  266,  266,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  266,  270,  271,  266,  271,  266,  266,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  266,  269,  269,  269,  266,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  266,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  266,  266,  266,  266,  266,  266,  266,
      269,  269,  266,  269,  269,  269,  269,  269,  269,  269,
      269,  266,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  266,  266,  266,  266,  266,  266,  266,  266,
      269,  266,  269,  269,  269,  269,  269,  269,  269,  269,
      266,  269,  269,  269,  269,  269,  266,  266,  266,  266,
      266,  266,  266,  269,  266,  269,  269,  269,  269,  266,
      269,  266,  266,  266,  266,  266,  269,  266,  269,  269,
      269,  266,  269,  266,  266,  266,  266,  269,  266,  269,
      266,  266,  266,  266,  266,    0,  266,  266,  266,  266,
      266
    } ;

static yyconst short int yy_nxt[390] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   32,   33,   34,
       35,   36,   32,   37,   38,   39,   40,   32,   41,   42,
       43,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   44,
       32,   32,   32,   45,   46,   47,   51,   52,   51,   52,
       54,   56,   56,   61,   63,   55,   66,   68,   71,   69,
       67,   64,   62,   74,   78,   89,   65,   81,   70,   75,
       72,   85,   90,   56,   56,   73,   86,   79,   87,   82,

       83,   97,   97,  107,   84,  101,  102,   97,   97,   97,
       97,   97,   97,  116,  117,  122,  119,  108,  126,  128,
      133,  142,  142,  129,   59,  123,  146,  146,  127,   53,
      265,   53,  120,  134,   97,   97,  158,  158,  264,  207,
       97,   97,   97,   97,   97,   97,  171,  174,  175,  263,
      172,  176,  208,  177,  262,  261,  260,  178,  179,  259,
      258,  180,   48,   48,   48,   48,   50,   50,   50,   50,
       93,  257,   93,   93,   94,  256,  255,   94,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,

      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      173,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  145,  144,  143,  141,  140,  139,
      138,  137,  136,  135,   98,   96,   92,  132,  131,  130,
      125,  124,  121,  118,  115,  114,  113,  112,  111,  110,

      109,  106,  105,  104,  103,  100,   99,   98,   96,   95,
       92,   91,   88,   80,   77,   76,   60,   58,   57,  266,
       49,   49,    7,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static yyconst short int yy_chk[390] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
       11,   21,   21,   27,   28,   11,   29,   30,   31,   30,
       29,   28,   27,   33,   36,   41,   28,   38,   30,   33,
       31,   39,   41,   56,   56,   31,   39,   36,   39,   38,

       38,   54,   54,   69,   38,   63,   63,   54,   54,   54,
       54,   54,   54,   78,   78,   82,   80,   69,   85,   87,
       91,  107,  107,   87,  269,   82,  111,  111,   85,    5,
      264,    6,   80,   91,   97,   97,  124,  124,  261,  178,
       97,   97,   97,   97,   97,   97,  140,  142,  142,  256,
      140,  142,  178,  142,  255,  254,  253,  142,  142,  252,
      247,  142,  267,  267,  267,  267,  268,  268,  268,  268,
      270,  246,  270,  270,  271,  245,  244,  271,  243,  241,
      240,  239,  238,  236,  235,  234,  233,  230,  229,  228,
      227,  223,  221,  217,  216,  214,  213,  212,  211,  210,

      209,  208,  207,  206,  204,  203,  201,  200,  198,  197,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  181,  180,  179,  177,  176,  175,  174,  173,  171,
      168,  167,  166,  165,  164,  163,  161,  159,  158,  157,
      155,  154,  153,  152,  150,  148,  147,  146,  145,  144,
      141,  138,  136,  135,  134,  133,  132,  131,  130,  128,
      127,  126,  125,  123,  122,  121,  120,  119,  118,  117,
      115,  114,  113,  112,  110,  109,  108,  106,  104,  103,
      102,  101,  100,   99,   98,   96,   92,   90,   89,   88,
       84,   83,   81,   79,   77,   76,   75,   73,   72,   71,

       70,   68,   66,   65,   64,   62,   61,   55,   53,   52,
       47,   44,   40,   37,   35,   34,   26,   25,   23,    7,
        4,    3,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "vb_lark.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 5 "vb_lark.l"
  #include <stdlib.h>
  #include <stdio.h>
  #include <string.h>
  #include "vb_lark_tab.h"
  
  extern int yyparse(void);
  extern int print_tree();
  
  //extern FILE* file;
  char literal[100];
  int num = 0;
#define COMMENT 1

#define STRING 2

#line 555 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "vb_lark.l"


#line 705 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 323 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "vb_lark.l"
{
                          // fprintf(file, "\nIncorrect characters:");
						   //fprintf(file, " %d:%d\n", yylloc.first_line, yylloc.first_column);
						   getchar();
						   exit(1);
						 }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "vb_lark.l"
{
                          //fprintf(file, "\nEnd line has found\n");
						   return ENDL;
						 }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "vb_lark.l"
{
                          //fprintf(file,"\nKeyword \"Dim\" has found\n");
						   return DIM;
						 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "vb_lark.l"
{
                          //fprintf(file,"\nKeyword \"Dim\" has found\n");
						   return SUB_MAIN_ENDL;
						 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"As\" has found\n");
						   return AS;
						 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"True\" has found\n");
						   return TRUE;
						 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"False\" has found\n");
						   return FALSE;
						 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"If\" has found\n");
						   return IF;
						 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Then\" has found\n");
						   return THEN;
						 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 73 "vb_lark.l"
{
                           //printf(file,"\nKeyword \"ElseIf\" has found\n");
						   return ELSEIF;
						 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Else\" has found\n");
						   return ELSE;
						 }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 83 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"End If\" has found\n");
						   return END_IF;
						 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Function\" has found\n");
						   return FUNCTION;
						 }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"ByVal\" has found\n");
						   return BYVAL;
						 }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Return\" has found\n");
						   return RETURN;
						 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "vb_lark.l"
{
                           //fprintf(file,"\nKeywords \"End Function\" has found\n");
						   return END_FUNCTION;
						 }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Sub\" has found\n");
						   return SUB;
						 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"End Sub\" has found\n");
						   return END_SUB;
						 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 118 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"Try\" has found\n");
						   return TRY;
						 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "vb_lark.l"
{
                           //fprintf(file,"\nKeywords \"Catch\" has found\n");
						   return CATCH;
						 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "vb_lark.l"
{
                           //fprintf(file,"\nKeywords \"End Try\" has found\n");
						   return END_TRY;
						 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 133 "vb_lark.l"
{
                           //fprintf(file,"\nKeywords \"Throw\" has found\n");
						   return THROW;
						 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 138 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Boolean\" has found\n");
						   return BOOLEAN;
						 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 143 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Integer\" has found\n");
						   return INTEGER;
						 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 148 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"New\" has found\n");
						   return NEW;
						 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 153 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Case\" has found\n");
						   return CASE;
						 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Char\" has found\n");
						   return CHAR;
						 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 163 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Const\" has found\n");
						   return CONST;
						 }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 168 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Select\" has found\n");
						   return SELECT;
						 }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 173 "vb_lark.l"
{
                           //fprintf(file,"\nKeywords \"Do While\" has found\n");
						   return WHILE;
						 }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 178 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"Do Until\" has found\n");
						   return UNTIL;
						 }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 183 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Module\" has found\n");
						   return MODULE;
						 }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 188 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Do\" has found\n");
						   return DO;
						 }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 192 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"Enum\" has found\n");
						   return ENUM;
						 }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 197 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"End Enum\" has found\n");
						   return END_ENUM;
						 }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 202 "vb_lark.l"
{
                           //fprintf(file,"\nKeywords \"End Module\" has found\n");
						   return END_MODULE;
						 }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 207 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"End Select\" has found\n");
						   return END_SELECT;
						 }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 212 "vb_lark.l"
{
                          // fprintf(file,"\nKeywords \"End While\" has found\n");
						   return END_WHILE;
						 }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 217 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"End While\" has found\n");
						   return LOOP;
						 }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 222 "vb_lark.l"
{
                         //  fprintf(file,"\nKeyword \"Step\" has found\n");
						   return STEP;
						 }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 227 "vb_lark.l"
{
                         //  fprintf(file,"\nKeywords \"For Each\" has found\n");
						   return FOR_EACH;
						 }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 232 "vb_lark.l"
{
                        //   fprintf(file,"\nKeyword \"For\" has found\n");
						   return FOR;
						 }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 237 "vb_lark.l"
{
                       //    fprintf(file,"\nKeyword \"To\" has found\n");
						   return TO;
						 }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 242 "vb_lark.l"
{
                        //   fprintf(file,"\nKeyword \"Next\" has found\n");
						   return NEXT;
						 }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 247 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"In\" has found\n");
						   return IN;
						 }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 252 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"String\" has found\n");
						   return STRING_T;
						 }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 257 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"Mod\" has found\n");
						   return MOD;
						 }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 262 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"Console\" has found\n");
						   return CONSOLE;
						 }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 267 "vb_lark.l"
{
                           //fprintf(file,"\nKeyword \"Write\" has found\n");
						   return WRITE;
						 }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 272 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"WriteLine\" has found\n");
						   return WRITELINE;
						 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 277 "vb_lark.l"
{ 
                          // fprintf(file,"\nKeyword \"Read\" has found\n");
						   return READ;
						 }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 282 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"ReadLine\" has found\n");
						   return READLINE;
						 }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 287 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"System\" has found\n");
						   return SYSTEM;
						 }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 292 "vb_lark.l"
{
                          // fprintf(file,"\nKeyword \"Exception\" has found\n");
						   return EXCEPTION;
						 }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 297 "vb_lark.l"
{
                          // fprintf(file,"\nOperator \"=\" has found\n");
						   return '=';
						 }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 302 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \"+\" has found\n");
						   return '+';
						 }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 307 "vb_lark.l"
{
                          // fprintf(file,"\nOperator \"-\" has found\n");
						   return '-';
						 }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 312 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \"*\" has found\n");
						   return '*';
						 }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 317 "vb_lark.l"
{
                       //    fprintf(file,"\nOperator \"\\\" has found\n");
						   return '\\';
						 }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 322 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \"/\" has found\n");
						   return '/';
						 }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 327 "vb_lark.l"
{
                          // fprintf(file,"\nOperator \"^\" has found\n");
						   return '^';
						 }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 332 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \">\" has found\n");
						   return '>';
						 }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 337 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \"<\" has found\n");
						   return '<';
						 }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 342 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \">=\" has found\n");
						   return MORE_OR_EQUAL;
						 }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 347 "vb_lark.l"
{
                        //   fprintf(file,"\nOperator \"<=\" has found\n");
						   return LESS_OR_EQUAL;
						 }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 352 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \"(\" has found\n");
						   return '(';
						 }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 357 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \")\" has found\n");
						   return ')';
						 }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 362 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \"{\" has found\n");
						   return '{';
						 }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 367 "vb_lark.l"
{
                          // fprintf(file,"\nOperator \"}\" has found\n");
						   return '}';
						 }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 372 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \",\" has found\n");
						   return ',';
						 }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 377 "vb_lark.l"
{
                         //  fprintf(file,"\nOperator \".\" has found\n");
						   return '.';
						 }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 382 "vb_lark.l"
{
                          // fprintf(file,"\nOperator \":\" has found\n");
						   return ':';
						 }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 387 "vb_lark.l"
{ BEGIN(COMMENT);                                                              }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 388 "vb_lark.l"
{ /*fprintf(file,"\nComment\n"); BEGIN(INITIAL);*/                                 }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 389 "vb_lark.l"
{                                                                              }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 391 "vb_lark.l"
{
                           strcpy(literal,"");
						   BEGIN(STRING);
						 }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 396 "vb_lark.l"
{
                           strcat(literal,yytext);
						 }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 400 "vb_lark.l"
{
                           //printf(file,"\nString has ended by \\n \"%s\"\n", literal);
						   BEGIN(INITIAL);
						 }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 405 "vb_lark.l"
{
                           strcat(literal,"\"");
						 }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 409 "vb_lark.l"
{
                          // fprintf(file, "\nIncorrect characters:");
						   //fprintf(file, " %d:%d\n", yylloc.first_line, yylloc.first_column);
						   getchar();
						   exit(1);
						 }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 416 "vb_lark.l"
{
                          // fprintf(file,"\nString literal \"%s\"",literal);
						   BEGIN(INITIAL);
						   yylval.s_const = (char*)malloc(strlen(literal)+1);
						   strcpy(yylval.s_const, literal);
						   return STRING_CONST;
						 }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 424 "vb_lark.l"
{
                           //fprintf(file,"\nSymbol \"\\n\" has found");
						   yylval.c_const = '\n';
						   return CHAR_CONST;
						 }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 430 "vb_lark.l"
{
                          // fprintf(file,"\nSymbol \"\\t\" has found");
						   yylval.c_const = '\t';
						   return CHAR_CONST;
						 }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 436 "vb_lark.l"
{
                          // fprintf(file,"\nSynbol \"\\0\" has found");
						   yylval.c_const = '\0';
						   return CHAR_CONST;
						 }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 442 "vb_lark.l"
{
                          // fprintf(file,"\nID %s has found\n", yytext);
						   yylval.s_const = (char*)malloc(strlen(yytext)+1);
						   strcpy(yylval.s_const, yytext);
						   return ID;
						 }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 449 "vb_lark.l"
{
                         //  fprintf(file,"\nNumber %d has found\n", atoi(yytext));
						   yylval.i_const = atoi(yytext);
						   return INT_CONST;
						 }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 455 "vb_lark.l"
{
                           sscanf(yytext, "%h", &num);
						  // fprintf(file,"\nNumber %d has found\n", num);
						   yylval.i_const = num;
						   return INT_CONST;
						 }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 462 "vb_lark.l"
{
                           sscanf(yytext, "%o", &num);
						  // fprintf(file,"\nNumber %d has found\n", num);
						   yylval.i_const = num;
						   return INT_CONST;
						 }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 470 "vb_lark.l"
ECHO;
	YY_BREAK
#line 1503 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 266);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 470 "vb_lark.l"



//int main (int argc, char* argv[])
//{
//	file = fopen("result.txt", "wt");
//	yyin = fopen(argv[1], "r");
//	
//	//yylex();	// ÇÀÌÅÍÅÍÅÍÎ
//	
//	yyparse();
//	
//	print_tree();		// Âûâîä äåðåâà
//	
//	fclose(file);
//	getchar();
//	return 0;
//}

// ÏÅÐÅÍÅÑÅÍÎ Â ÁÈÇÎÍÎÂÑÊÈÉ Ó-ÔÀÉË!!!

//int main(int argc, char* argv[])
//{
//  file = fopen("result.txt", "wt");
//  yyin = fopen(argv[1], "r");
//  yylex();
//  //yyparse();
//  fclose(file);
//  getchar();
//  return 0;
//}