/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include "stdafx.h"

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[230] =
    {   0,
        0,    0,   69,   69,    0,    0,   83,   82,   70,   82,
       67,   61,   62,   48,   46,   65,   47,   66,   50,   79,
       58,   45,   57,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   49,   51,   78,
       63,   64,   69,   68,   71,   72,   74,    0,    0,   54,
       52,   53,   56,   79,   60,   59,   78,   78,    2,   78,
       78,   78,   78,   78,   78,   31,   78,   78,   78,   78,
        3,   42,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   40,   78,   55,   78,   69,   71,   73,   80,   81,
       18,   78,   78,   78,   78,   78,   78,   78,   78,    1,

        0,   78,   78,   78,   39,   78,   78,   78,   44,   21,
       78,   78,   78,   78,   78,   12,   78,   78,   14,   78,
       78,   78,   78,   78,   23,   24,   78,   25,   78,    0,
        0,    6,    0,   32,    0,   78,   78,   37,   78,   41,
       78,   78,   78,   78,    4,   78,   78,   78,   78,   22,
        9,   15,   26,    0,    0,   78,    0,    0,    0,    0,
        0,    0,    0,    0,   78,   78,   78,   78,   78,   78,
       78,   17,   78,   76,   78,    0,    0,    5,    0,    0,
        7,    0,    0,    0,    0,    0,    0,   78,   78,   30,
       78,   10,   27,   43,   75,   19,    0,    0,    0,    0,

        0,    0,   13,   16,    0,    0,   78,   20,   78,   29,
       28,   33,    0,    0,    0,    0,   38,    8,   77,    0,
        0,    0,   36,    0,   34,   35,    0,   11,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   16,   16,    1,    1,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   26,   26,   29,   30,   31,   32,   26,
       26,   33,   34,   35,   36,   37,   38,   26,   26,   26,
        1,   39,    1,   40,   26,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   26,   26,   50,   51,   52,
       53,   54,   26,   55,   56,   57,   58,   59,   60,   61,
       62,   26,   63,    1,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1
    } ;

static yyconst short int yy_base[235] =
    {   0,
        0,    0,  282,  281,   62,   64,  283,  286,  286,   42,
      286,  286,  286,  264,  263,  286,  262,  286,  261,   55,
      260,  286,  259,   20,   20,   36,   26,   28,   28,    0,
       39,  223,  222,   38,  229,   42,   40,  255,  286,  230,
      286,  286,    0,  286,    0,  286,  267,   82,  255,  286,
      286,  286,  286,   93,  286,  286,    0,  225,    0,  215,
       57,   60,  226,  214,  214,  109,  208,   57,  208,  210,
        0,  204,  207,  215,   53,  208,  200,  206,  200,  212,
       73,    0,  191,  286,   97,    0,    0,  286,  114,  237,
        0,  201,  205,  208,  198,  202,  203,  190,  188,    0,

       84,  198,  121,  191,  123,  198,  195,  185,  180,    0,
      180,  186,  177,  189,  184,    0,  180,  178,    0,  175,
      188,  183,  181,  176,    0,    0,  177,    0,  167,  171,
      174,  193,  116,    0,  196,  162,  171,    0,  167,    0,
      194,  160,  171,  161,    0,  152,  182,  168,  168,    0,
        0,    0,    0,  151,  158,  160,  153,  146,  157,  149,
       97,  146,  152,  158,  149,  152,  151,  147,  142,  136,
      145,    0,  145,    0,  138,  140,  138,    0,  129,  134,
      286,  141,  134,  141,  120,  132,  137,  126,  123,    0,
      136,    0,    0,    0,    0,    0,  126,  130,  123,  130,

      114,  125,  286,  286,  119,  117,  101,    0,   97,  286,
      286,  286,   92,   98,  104,  100,  286,    0,    0,   94,
       88,   74,  286,   74,  286,  286,   69,  286,  286,  155,
      159,   88,  163,  167
    } ;

static yyconst short int yy_def[235] =
    {   0,
      229,    1,  230,  230,  231,  231,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  229,  229,  232,
      229,  229,  233,  229,  234,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  229,  232,  233,  234,  229,  229,  229,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      229,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  229,
      229,  232,  229,  232,  229,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  229,  229,  232,  229,  229,  229,  229,
      229,  229,  229,  229,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  229,  229,  232,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  232,  232,  232,  229,
      229,  229,  229,  229,  229,  229,  229,  232,  232,  229,
      229,  229,  229,  229,  229,  229,  229,  229,    0,  229,
      229,  229,  229,  229
    } ;

static yyconst short int yy_nxt[351] =
    {   0,
        8,    8,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   30,   35,   36,   37,   30,   30,   30,   38,   39,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   40,   30,
       30,   30,   41,   42,   46,   47,   46,   47,   48,   54,
       54,   58,   60,   49,   65,   59,   62,   67,   66,   68,
       69,   61,   75,   63,   71,   70,   78,   81,   64,   93,
       72,   57,   82,   94,   83,   76,   89,   89,   79,   80,

      103,   89,   89,   89,   89,   89,   89,   54,   54,   95,
      101,  101,  110,  111,  104,   96,   97,  117,  120,  130,
      228,  131,  133,  133,  135,  135,  227,  118,   89,   89,
      226,  121,  225,   89,   89,   89,   89,   89,   89,  157,
      158,  183,  224,  159,  223,  160,  222,  221,  220,  161,
      162,  219,  218,  163,  184,   43,   43,   43,   43,   45,
       45,   45,   45,   86,  217,   86,   86,   87,  216,  215,
       87,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,

      185,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  134,  132,  129,  128,  127,  126,  125,  124,  123,
      122,   90,  119,  116,  115,  114,  113,  112,  109,  108,
      107,  106,  105,  102,  100,   99,   98,   92,   91,   90,
       88,   85,   84,   77,   74,   73,   56,   55,   53,   52,
       51,   50,  229,   44,   44,    7,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229
    } ;

static yyconst short int yy_chk[351] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,   10,   20,
       20,   24,   25,   10,   27,   24,   26,   28,   27,   28,
       29,   25,   34,   26,   31,   29,   36,   37,   26,   61,
       31,  232,   37,   61,   37,   34,   48,   48,   36,   36,

       68,   48,   48,   48,   48,   48,   48,   54,   54,   62,
       66,   66,   75,   75,   68,   62,   62,   81,   85,  101,
      227,  101,  103,  103,  105,  105,  224,   81,   89,   89,
      222,   85,  221,   89,   89,   89,   89,   89,   89,  133,
      133,  161,  220,  133,  216,  133,  215,  214,  213,  133,
      133,  209,  207,  133,  161,  230,  230,  230,  230,  231,
      231,  231,  231,  233,  206,  233,  233,  234,  205,  202,
      234,  201,  200,  199,  198,  197,  191,  189,  188,  187,
      186,  185,  184,  183,  182,  180,  179,  177,  176,  175,
      173,  171,  170,  169,  168,  167,  166,  165,  164,  163,

      162,  160,  159,  158,  157,  156,  155,  154,  149,  148,
      147,  146,  144,  143,  142,  141,  139,  137,  136,  135,
      132,  131,  130,  129,  127,  124,  123,  122,  121,  120,
      118,  117,  115,  114,  113,  112,  111,  109,  108,  107,
      106,  104,  102,   99,   98,   97,   96,   95,   94,   93,
       92,   90,   83,   80,   79,   78,   77,   76,   74,   73,
       72,   70,   69,   67,   65,   64,   63,   60,   58,   49,
       47,   40,   38,   35,   33,   32,   23,   21,   19,   17,
       15,   14,    7,    4,    3,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "vb_lark.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 5 "vb_lark.l"
  #include <stdlib.h>
  #include <stdio.h>
  #include <string.h>
  
  FILE* file;
  char literal[100];
  int num = 0;
#define COMMENT 1

#define STRING 2

#line 531 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 20 "vb_lark.l"


#line 681 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 230 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 286 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Dim\" has found\n");                               }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "vb_lark.l"
{ fprintf(file,"\nKeyword \"As\" has found\n");                                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "vb_lark.l"
{ fprintf(file,"\nKeyword \"If\" has found\n");                                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Then\" has found\n");                              }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "vb_lark.l"
{ fprintf(file,"\nKeyword \"ElseIf\" has found\n");                            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Else\" has found\n");                              }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End If\" has found\n");                           }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Function\" has found\n");                          }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "vb_lark.l"
{ fprintf(file,"\nKeyword \"ByVal\" has found\n");                             }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Return\" has found\n");                            }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End Function\" has found\n");                     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Sub\" has found\n");                               }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End Sub\" has found\n");                          }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "vb_lark.l"
{ fprintf(file,"\nKeywords \"Try\" has found\n");                              }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "vb_lark.l"
{ fprintf(file,"\nKeywords \"Catch\" has found\n");                            }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End Try\" has found\n");                          }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "vb_lark.l"
{ fprintf(file,"\nKeywords \"Throw\" has found\n");                            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "vb_lark.l"
{ fprintf(file,"\nKeyword \"And\" has found\n");                               }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Boolean\" has found\n");                           }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Integer\" has found\n");                           }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "vb_lark.l"
{ fprintf(file,"\nKeyword \"New\" has found\n");                               }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "vb_lark.l"
{ fprintf(file,"\nKeyword \"ByRef\" has found\n");                             }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Call\" has found\n");                              }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Case\" has found\n");                              }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Char\" has found\n");                              }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Const\" has found\n");                             }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Select\" has found\n");                            }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "vb_lark.l"
{ fprintf(file,"\nKeywords \"Do While\" has found\n");                         }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "vb_lark.l"
{ fprintf(file,"\nKeywords \"Do Until\" has found\n");                         }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Module\" has found\n");                            }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Do\" has found\n");                                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Enum\" has found\n");                              }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End Enum\" has found\n");                         }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End Module\" has found\n");                       }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End Select\" has found\n");                       }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "vb_lark.l"
{ fprintf(file,"\nKeywords \"End While\" has found\n");                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "vb_lark.l"
{ fprintf(file,"\nKeyword \"End While\" has found\n");                         }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "vb_lark.l"
{ fprintf(file,"\nKeywords \"For Each\" has found\n");                         }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "vb_lark.l"
{ fprintf(file,"\nKeyword \"For\" has found\n");                               }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "vb_lark.l"
{ fprintf(file,"\nKeyword \"To\" has found\n");                                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Next\" has found\n");                              }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "vb_lark.l"
{ fprintf(file,"\nKeyword \"In\" has found\n");                                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "vb_lark.l"
{ fprintf(file,"\nKeyword \"String\" has found\n");                            }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "vb_lark.l"
{ fprintf(file,"\nKeyword \"Mod\" has found\n");                               }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "vb_lark.l"
{ fprintf(file,"\nOperator \"=\" has found\n");                                }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 68 "vb_lark.l"
{ fprintf(file,"\nOperator \"+\" has found\n");                                }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 69 "vb_lark.l"
{ fprintf(file,"\nOperator \"-\" has found\n");                                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 70 "vb_lark.l"
{ fprintf(file,"\nOperator \"*\" has found\n");                                }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 71 "vb_lark.l"
{ fprintf(file,"\nOperator \"\\\" has found\n");                               }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "vb_lark.l"
{ fprintf(file,"\nOperator \"/\" has found\n");                                }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 73 "vb_lark.l"
{ fprintf(file,"\nOperator \"^\" has found\n");                                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 74 "vb_lark.l"
{ fprintf(file,"\nOperator \"+=\" has found\n");                               }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 75 "vb_lark.l"
{ fprintf(file,"\nOperator \"-=\" has found\n");                               }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 76 "vb_lark.l"
{ fprintf(file,"\nOperator \"*=\" has found\n");                               }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 77 "vb_lark.l"
{ fprintf(file,"\nOperator \"\\=\" has found\n");                              }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 78 "vb_lark.l"
{ fprintf(file,"\nOperator \"/=\" has found\n");                               }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 79 "vb_lark.l"
{ fprintf(file,"\nOperator \">\" has found\n");                                }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 80 "vb_lark.l"
{ fprintf(file,"\nOperator \"<\" has found\n");                                }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 81 "vb_lark.l"
{ fprintf(file,"\nOperator \">=\" has found\n");                               }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 82 "vb_lark.l"
{ fprintf(file,"\nOperator \"<=\" has found\n");                               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "vb_lark.l"
{ fprintf(file,"\nOperator \"(\" has found\n");                                }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "vb_lark.l"
{ fprintf(file,"\nOperator \")\" has found\n");                                }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "vb_lark.l"
{ fprintf(file,"\nOperator \"{\" has found\n");                                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "vb_lark.l"
{ fprintf(file,"\nOperator \"}\" has found\n");                                }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 89 "vb_lark.l"
{ fprintf(file,"\nOperator \",\" has found\n");                                }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 90 "vb_lark.l"
{ fprintf(file,"\nOperator \".\" has found\n");                                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 92 "vb_lark.l"
{ BEGIN(COMMENT);                                                              }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 93 "vb_lark.l"
{ fprintf(file,"\nComment\n"); BEGIN(INITIAL);                                 }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 94 "vb_lark.l"
{                                                                              }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 96 "vb_lark.l"
{ strcpy(literal,""); BEGIN(STRING);                                           }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 97 "vb_lark.l"
{ strcat(literal,yytext);                                                      }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 98 "vb_lark.l"
{ fprintf(file,"\nString has ended by \\n \"%s\"\n", literal); BEGIN(INITIAL); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 99 "vb_lark.l"
{ strcat(literal,"\"");                                                        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 100 "vb_lark.l"
{ fprintf(file,"\nString literal \"%s\"",literal); BEGIN(INITIAL);             }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 101 "vb_lark.l"
{ fprintf(file,"\nSymbol \"\\n\" has found");                                  }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 102 "vb_lark.l"
{ fprintf(file,"\nSymbol \"\\t\" has found");                                  }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 103 "vb_lark.l"
{ fprintf(file,"\nSynbol \"\\0\" has found");                                  }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "vb_lark.l"
{ fprintf(file,"\nID %s has found\n", yytext);                                 }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 107 "vb_lark.l"
{ fprintf(file,"\nNumber %d has found\n", atoi(yytext));                       }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 108 "vb_lark.l"
{ sscanf(yytext, "%h", &num); fprintf(file,"\nNumber %d has found\n", num);    }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 109 "vb_lark.l"
{ sscanf(yytext, "%o", &num); fprintf(file,"\nNumber %d has found\n", num);    }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 112 "vb_lark.l"
ECHO;
	YY_BREAK
#line 1174 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 230 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 230 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 229);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 112 "vb_lark.l"

int main(int argc, char* argv[])
{
  file = fopen("result.txt", "wt");
  yyin = fopen(argv[1], "r");
  yylex();
  fclose(file);
  getchar();
  return 0;
}